In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv('/kaggle/input/titanic-dataset/Titanic-Dataset.csv')

In [3]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
data['Name'].isnull().sum()

0

In [6]:
data=data.drop(columns='Name')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [8]:
data=pd.get_dummies(data,columns=['Sex'])

In [9]:
data['Age'].isnull().sum()

177

In [10]:
data.shape

(891, 12)

In [11]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
data['Age']=data['Age'].fillna(data['Age'].mean())

In [13]:
data['Age'].isnull().sum()

0

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Age          891 non-null    float64
 4   SibSp        891 non-null    int64  
 5   Parch        891 non-null    int64  
 6   Ticket       891 non-null    object 
 7   Fare         891 non-null    float64
 8   Cabin        204 non-null    object 
 9   Embarked     889 non-null    object 
 10  Sex_female   891 non-null    bool   
 11  Sex_male     891 non-null    bool   
dtypes: bool(2), float64(2), int64(5), object(3)
memory usage: 71.5+ KB


In [15]:
data=data.drop(columns='SibSp')


In [16]:
data['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [17]:
data=data.drop(columns='Ticket')

In [18]:
data['Fare'].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [19]:
data['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [20]:
data['Cabin_initial'] = data['Cabin'].astype(str).str[0]

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   PassengerId    891 non-null    int64  
 1   Survived       891 non-null    int64  
 2   Pclass         891 non-null    int64  
 3   Age            891 non-null    float64
 4   Parch          891 non-null    int64  
 5   Fare           891 non-null    float64
 6   Cabin          204 non-null    object 
 7   Embarked       889 non-null    object 
 8   Sex_female     891 non-null    bool   
 9   Sex_male       891 non-null    bool   
 10  Cabin_initial  891 non-null    object 
dtypes: bool(2), float64(2), int64(4), object(3)
memory usage: 64.5+ KB


In [22]:
data['Cabin_initial'].unique()

array(['n', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [23]:
data=pd.get_dummies(data,columns=['Cabin_initial'])

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   PassengerId      891 non-null    int64  
 1   Survived         891 non-null    int64  
 2   Pclass           891 non-null    int64  
 3   Age              891 non-null    float64
 4   Parch            891 non-null    int64  
 5   Fare             891 non-null    float64
 6   Cabin            204 non-null    object 
 7   Embarked         889 non-null    object 
 8   Sex_female       891 non-null    bool   
 9   Sex_male         891 non-null    bool   
 10  Cabin_initial_A  891 non-null    bool   
 11  Cabin_initial_B  891 non-null    bool   
 12  Cabin_initial_C  891 non-null    bool   
 13  Cabin_initial_D  891 non-null    bool   
 14  Cabin_initial_E  891 non-null    bool   
 15  Cabin_initial_F  891 non-null    bool   
 16  Cabin_initial_G  891 non-null    bool   
 17  Cabin_initial_T 

In [25]:
data=data.drop(columns='Cabin')

In [26]:
data['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [27]:
data['Embarked'].isnull().sum()

2

In [28]:
data.dropna(subset='Embarked',inplace=True)

In [29]:
data=pd.get_dummies(data,columns=['Embarked'])

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   PassengerId      889 non-null    int64  
 1   Survived         889 non-null    int64  
 2   Pclass           889 non-null    int64  
 3   Age              889 non-null    float64
 4   Parch            889 non-null    int64  
 5   Fare             889 non-null    float64
 6   Sex_female       889 non-null    bool   
 7   Sex_male         889 non-null    bool   
 8   Cabin_initial_A  889 non-null    bool   
 9   Cabin_initial_B  889 non-null    bool   
 10  Cabin_initial_C  889 non-null    bool   
 11  Cabin_initial_D  889 non-null    bool   
 12  Cabin_initial_E  889 non-null    bool   
 13  Cabin_initial_F  889 non-null    bool   
 14  Cabin_initial_G  889 non-null    bool   
 15  Cabin_initial_T  889 non-null    bool   
 16  Cabin_initial_n  889 non-null    bool   
 17  Embarked_C       889 

In [31]:
data.isnull().sum()

PassengerId        0
Survived           0
Pclass             0
Age                0
Parch              0
Fare               0
Sex_female         0
Sex_male           0
Cabin_initial_A    0
Cabin_initial_B    0
Cabin_initial_C    0
Cabin_initial_D    0
Cabin_initial_E    0
Cabin_initial_F    0
Cabin_initial_G    0
Cabin_initial_T    0
Cabin_initial_n    0
Embarked_C         0
Embarked_Q         0
Embarked_S         0
dtype: int64

In [32]:
data.duplicated().sum()

0

In [33]:
data.drop_duplicates(inplace=True)

In [34]:
x=data.drop(columns='Survived')
y=data['Survived']

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2)

In [36]:
model=LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [37]:
pred=model.predict(x_test)

In [38]:
accuracy = accuracy_score(y_test, pred)
print("Accuracy:", accuracy)

Accuracy: 0.7528089887640449


In [39]:
ids = data['PassengerId'].copy()
submission = pd.DataFrame({
    'PassengerId': ids[:len(pred)],
    'Survived': pred
})

In [40]:
submission.to_csv('submission.csv', index=False)

In [41]:
len(pred)

178

In [42]:
test_features = data.drop(columns=['PassengerId'])

In [43]:
test_features = test_features.fillna(0)